import { InferGetStaticPropsType } from "next";
import Head from "next/head";
import { ProjectList } from "@/components/project-list";
import client from "../../tina/__generated__/client";
import { Project } from "@/types/project";
import { Content } from "@/features/content";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home({ projects }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content>
          Привет, я Вика 👋 Я дизайню в Яндексе 🦾 Также делала посты для Purpur, мерч для Цех Live и афиши для инди групп 🕺
        </Content>
        <ProjectList projects={projects} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  let projects = [] as Project[];

  try {
    const res = await client.queries?.projectConnection();
    projects =
      res.data.projectConnection.edges?.map((project) => ({
        slug: project?.node?._sys.filename ?? "",
        title: project?.node?.title ?? "",
        thumbnail: project?.node?.thumbnail ?? "",
        body: [],
        gallery: [],
      })) ?? [];
  } catch {
    // swallow errors related to document creation
  }

  const props = {
    projects,
  };

  return {
    props,
  };
};
